//! Input domain types.
//!
//! The Input domain provides methods for simulating user input events.

use serde::Serialize;

/// Mouse button type.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum MouseButton {
    None,
    Left,
    Middle,
    Right,
    Back,
    Forward,
}

/// Type of mouse event.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum MouseEventType {
    MousePressed,
    MouseReleased,
    MouseMoved,
    MouseWheel,
}

/// Type of key event.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum KeyEventType {
    KeyDown,
    KeyUp,
    RawKeyDown,
    Char,
}

/// Parameters for Input.dispatchMouseEvent.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchMouseEventParams {
    /// Type of the mouse event.
    #[serde(rename = "type")]
    pub event_type: MouseEventType,
    /// X coordinate of the event relative to the main frame's viewport.
    pub x: f64,
    /// Y coordinate of the event relative to the main frame's viewport.
    pub y: f64,
    /// Mouse button.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button: Option<MouseButton>,
    /// Number of times the mouse button was clicked.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i32>,
    /// Bit field representing pressed modifier keys.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<i32>,
    /// Time at which the event occurred.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
}

impl DispatchMouseEventParams {
    /// Create a mouse move event.
    pub fn mouse_move(x: f64, y: f64) -> Self {
        Self {
            event_type: MouseEventType::MouseMoved,
            x,
            y,
            button: None,
            click_count: None,
            modifiers: None,
            timestamp: None,
        }
    }

    /// Create a mouse down event.
    pub fn mouse_down(x: f64, y: f64, button: MouseButton) -> Self {
        Self {
            event_type: MouseEventType::MousePressed,
            x,
            y,
            button: Some(button),
            click_count: Some(1),
            modifiers: None,
            timestamp: None,
        }
    }

    /// Create a mouse up event.
    pub fn mouse_up(x: f64, y: f64, button: MouseButton) -> Self {
        Self {
            event_type: MouseEventType::MouseReleased,
            x,
            y,
            button: Some(button),
            click_count: Some(1),
            modifiers: None,
            timestamp: None,
        }
    }
}

/// Parameters for Input.dispatchKeyEvent.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchKeyEventParams {
    /// Type of the key event.
    #[serde(rename = "type")]
    pub event_type: KeyEventType,
    /// Bit field representing pressed modifier keys.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<i32>,
    /// Time at which the event occurred.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
    /// Text as generated by processing a virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Text that would have been generated without any modifiers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unmodified_text: Option<String>,
    /// Unique key identifier.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_identifier: Option<String>,
    /// Unique DOM defined string value for each key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Unique DOM defined string value describing the meaning of the key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Windows virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub windows_virtual_key_code: Option<i32>,
    /// Native virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_virtual_key_code: Option<i32>,
    /// Whether the event was generated from auto repeat.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_repeat: Option<bool>,
    /// Whether the event was generated from the keypad.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_keypad: Option<bool>,
    /// Whether the event was a system key event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_system_key: Option<bool>,
    /// Editing commands to send with the event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commands: Option<Vec<String>>,
}

impl DispatchKeyEventParams {
    /// Create a key down event.
    pub fn key_down(key: &str) -> Self {
        Self {
            event_type: KeyEventType::KeyDown,
            modifiers: None,
            timestamp: None,
            text: None,
            unmodified_text: None,
            key_identifier: None,
            code: Some(key.to_string()),
            key: Some(key.to_string()),
            windows_virtual_key_code: None,
            native_virtual_key_code: None,
            auto_repeat: None,
            is_keypad: None,
            is_system_key: None,
            commands: None,
        }
    }

    /// Create a key up event.
    pub fn key_up(key: &str) -> Self {
        Self {
            event_type: KeyEventType::KeyUp,
            modifiers: None,
            timestamp: None,
            text: None,
            unmodified_text: None,
            key_identifier: None,
            code: Some(key.to_string()),
            key: Some(key.to_string()),
            windows_virtual_key_code: None,
            native_virtual_key_code: None,
            auto_repeat: None,
            is_keypad: None,
            is_system_key: None,
            commands: None,
        }
    }

    /// Create a char event for text input.
    pub fn char(text: &str) -> Self {
        Self {
            event_type: KeyEventType::Char,
            modifiers: None,
            timestamp: None,
            text: Some(text.to_string()),
            unmodified_text: Some(text.to_string()),
            key_identifier: None,
            code: None,
            key: None,
            windows_virtual_key_code: None,
            native_virtual_key_code: None,
            auto_repeat: None,
            is_keypad: None,
            is_system_key: None,
            commands: None,
        }
    }
}

/// Parameters for Input.insertText.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InsertTextParams {
    /// The text to insert.
    pub text: String,
}

/// Modifier keys bit flags.
pub mod modifiers {
    pub const ALT: i32 = 1;
    pub const CTRL: i32 = 2;
    pub const META: i32 = 4;
    pub const SHIFT: i32 = 8;
}
