//! Key definition type for keyboard input.

/// Key definition with all required properties for CDP.
#[derive(Debug, Clone)]
pub struct KeyDefinition {
    /// The key code (e.g., "`KeyA`", "Enter").
    pub code: &'static str,
    /// The key value (e.g., "a", "Enter").
    pub key: &'static str,
    /// Windows virtual key code.
    pub key_code: i32,
    /// The text generated by this key (if any).
    pub text: Option<&'static str>,
    /// Whether this key is on the keypad.
    pub is_keypad: bool,
    /// The location of the key (0 = standard, 1 = left, 2 = right, 3 = numpad).
    pub location: i32,
}
