//! Letter key definitions (a-z, A-Z).

use super::definition::KeyDefinition;

/// Get lowercase letter key definitions.
pub fn get_lowercase_letter_key(key: &str) -> Option<KeyDefinition> {
    Some(match key {
        "KeyA" | "a" => KeyDefinition {
            code: "KeyA",
            key: "a",
            key_code: 65,
            text: Some("a"),
            is_keypad: false,
            location: 0,
        },
        "KeyB" | "b" => KeyDefinition {
            code: "KeyB",
            key: "b",
            key_code: 66,
            text: Some("b"),
            is_keypad: false,
            location: 0,
        },
        "KeyC" | "c" => KeyDefinition {
            code: "KeyC",
            key: "c",
            key_code: 67,
            text: Some("c"),
            is_keypad: false,
            location: 0,
        },
        "KeyD" | "d" => KeyDefinition {
            code: "KeyD",
            key: "d",
            key_code: 68,
            text: Some("d"),
            is_keypad: false,
            location: 0,
        },
        "KeyE" | "e" => KeyDefinition {
            code: "KeyE",
            key: "e",
            key_code: 69,
            text: Some("e"),
            is_keypad: false,
            location: 0,
        },
        "KeyF" | "f" => KeyDefinition {
            code: "KeyF",
            key: "f",
            key_code: 70,
            text: Some("f"),
            is_keypad: false,
            location: 0,
        },
        "KeyG" | "g" => KeyDefinition {
            code: "KeyG",
            key: "g",
            key_code: 71,
            text: Some("g"),
            is_keypad: false,
            location: 0,
        },
        "KeyH" | "h" => KeyDefinition {
            code: "KeyH",
            key: "h",
            key_code: 72,
            text: Some("h"),
            is_keypad: false,
            location: 0,
        },
        "KeyI" | "i" => KeyDefinition {
            code: "KeyI",
            key: "i",
            key_code: 73,
            text: Some("i"),
            is_keypad: false,
            location: 0,
        },
        "KeyJ" | "j" => KeyDefinition {
            code: "KeyJ",
            key: "j",
            key_code: 74,
            text: Some("j"),
            is_keypad: false,
            location: 0,
        },
        "KeyK" | "k" => KeyDefinition {
            code: "KeyK",
            key: "k",
            key_code: 75,
            text: Some("k"),
            is_keypad: false,
            location: 0,
        },
        "KeyL" | "l" => KeyDefinition {
            code: "KeyL",
            key: "l",
            key_code: 76,
            text: Some("l"),
            is_keypad: false,
            location: 0,
        },
        "KeyM" | "m" => KeyDefinition {
            code: "KeyM",
            key: "m",
            key_code: 77,
            text: Some("m"),
            is_keypad: false,
            location: 0,
        },
        "KeyN" | "n" => KeyDefinition {
            code: "KeyN",
            key: "n",
            key_code: 78,
            text: Some("n"),
            is_keypad: false,
            location: 0,
        },
        "KeyO" | "o" => KeyDefinition {
            code: "KeyO",
            key: "o",
            key_code: 79,
            text: Some("o"),
            is_keypad: false,
            location: 0,
        },
        "KeyP" | "p" => KeyDefinition {
            code: "KeyP",
            key: "p",
            key_code: 80,
            text: Some("p"),
            is_keypad: false,
            location: 0,
        },
        "KeyQ" | "q" => KeyDefinition {
            code: "KeyQ",
            key: "q",
            key_code: 81,
            text: Some("q"),
            is_keypad: false,
            location: 0,
        },
        "KeyR" | "r" => KeyDefinition {
            code: "KeyR",
            key: "r",
            key_code: 82,
            text: Some("r"),
            is_keypad: false,
            location: 0,
        },
        "KeyS" | "s" => KeyDefinition {
            code: "KeyS",
            key: "s",
            key_code: 83,
            text: Some("s"),
            is_keypad: false,
            location: 0,
        },
        "KeyT" | "t" => KeyDefinition {
            code: "KeyT",
            key: "t",
            key_code: 84,
            text: Some("t"),
            is_keypad: false,
            location: 0,
        },
        "KeyU" | "u" => KeyDefinition {
            code: "KeyU",
            key: "u",
            key_code: 85,
            text: Some("u"),
            is_keypad: false,
            location: 0,
        },
        "KeyV" | "v" => KeyDefinition {
            code: "KeyV",
            key: "v",
            key_code: 86,
            text: Some("v"),
            is_keypad: false,
            location: 0,
        },
        "KeyW" | "w" => KeyDefinition {
            code: "KeyW",
            key: "w",
            key_code: 87,
            text: Some("w"),
            is_keypad: false,
            location: 0,
        },
        "KeyX" | "x" => KeyDefinition {
            code: "KeyX",
            key: "x",
            key_code: 88,
            text: Some("x"),
            is_keypad: false,
            location: 0,
        },
        "KeyY" | "y" => KeyDefinition {
            code: "KeyY",
            key: "y",
            key_code: 89,
            text: Some("y"),
            is_keypad: false,
            location: 0,
        },
        "KeyZ" | "z" => KeyDefinition {
            code: "KeyZ",
            key: "z",
            key_code: 90,
            text: Some("z"),
            is_keypad: false,
            location: 0,
        },
        _ => return None,
    })
}

/// Get uppercase letter key definitions.
pub fn get_uppercase_letter_key(key: &str) -> Option<KeyDefinition> {
    Some(match key {
        "A" => KeyDefinition {
            code: "KeyA",
            key: "A",
            key_code: 65,
            text: Some("A"),
            is_keypad: false,
            location: 0,
        },
        "B" => KeyDefinition {
            code: "KeyB",
            key: "B",
            key_code: 66,
            text: Some("B"),
            is_keypad: false,
            location: 0,
        },
        "C" => KeyDefinition {
            code: "KeyC",
            key: "C",
            key_code: 67,
            text: Some("C"),
            is_keypad: false,
            location: 0,
        },
        "D" => KeyDefinition {
            code: "KeyD",
            key: "D",
            key_code: 68,
            text: Some("D"),
            is_keypad: false,
            location: 0,
        },
        "E" => KeyDefinition {
            code: "KeyE",
            key: "E",
            key_code: 69,
            text: Some("E"),
            is_keypad: false,
            location: 0,
        },
        "F" => KeyDefinition {
            code: "KeyF",
            key: "F",
            key_code: 70,
            text: Some("F"),
            is_keypad: false,
            location: 0,
        },
        "G" => KeyDefinition {
            code: "KeyG",
            key: "G",
            key_code: 71,
            text: Some("G"),
            is_keypad: false,
            location: 0,
        },
        "H" => KeyDefinition {
            code: "KeyH",
            key: "H",
            key_code: 72,
            text: Some("H"),
            is_keypad: false,
            location: 0,
        },
        "I" => KeyDefinition {
            code: "KeyI",
            key: "I",
            key_code: 73,
            text: Some("I"),
            is_keypad: false,
            location: 0,
        },
        "J" => KeyDefinition {
            code: "KeyJ",
            key: "J",
            key_code: 74,
            text: Some("J"),
            is_keypad: false,
            location: 0,
        },
        "K" => KeyDefinition {
            code: "KeyK",
            key: "K",
            key_code: 75,
            text: Some("K"),
            is_keypad: false,
            location: 0,
        },
        "L" => KeyDefinition {
            code: "KeyL",
            key: "L",
            key_code: 76,
            text: Some("L"),
            is_keypad: false,
            location: 0,
        },
        "M" => KeyDefinition {
            code: "KeyM",
            key: "M",
            key_code: 77,
            text: Some("M"),
            is_keypad: false,
            location: 0,
        },
        "N" => KeyDefinition {
            code: "KeyN",
            key: "N",
            key_code: 78,
            text: Some("N"),
            is_keypad: false,
            location: 0,
        },
        "O" => KeyDefinition {
            code: "KeyO",
            key: "O",
            key_code: 79,
            text: Some("O"),
            is_keypad: false,
            location: 0,
        },
        "P" => KeyDefinition {
            code: "KeyP",
            key: "P",
            key_code: 80,
            text: Some("P"),
            is_keypad: false,
            location: 0,
        },
        "Q" => KeyDefinition {
            code: "KeyQ",
            key: "Q",
            key_code: 81,
            text: Some("Q"),
            is_keypad: false,
            location: 0,
        },
        "R" => KeyDefinition {
            code: "KeyR",
            key: "R",
            key_code: 82,
            text: Some("R"),
            is_keypad: false,
            location: 0,
        },
        "S" => KeyDefinition {
            code: "KeyS",
            key: "S",
            key_code: 83,
            text: Some("S"),
            is_keypad: false,
            location: 0,
        },
        "T" => KeyDefinition {
            code: "KeyT",
            key: "T",
            key_code: 84,
            text: Some("T"),
            is_keypad: false,
            location: 0,
        },
        "U" => KeyDefinition {
            code: "KeyU",
            key: "U",
            key_code: 85,
            text: Some("U"),
            is_keypad: false,
            location: 0,
        },
        "V" => KeyDefinition {
            code: "KeyV",
            key: "V",
            key_code: 86,
            text: Some("V"),
            is_keypad: false,
            location: 0,
        },
        "W" => KeyDefinition {
            code: "KeyW",
            key: "W",
            key_code: 87,
            text: Some("W"),
            is_keypad: false,
            location: 0,
        },
        "X" => KeyDefinition {
            code: "KeyX",
            key: "X",
            key_code: 88,
            text: Some("X"),
            is_keypad: false,
            location: 0,
        },
        "Y" => KeyDefinition {
            code: "KeyY",
            key: "Y",
            key_code: 89,
            text: Some("Y"),
            is_keypad: false,
            location: 0,
        },
        "Z" => KeyDefinition {
            code: "KeyZ",
            key: "Z",
            key_code: 90,
            text: Some("Z"),
            is_keypad: false,
            location: 0,
        },
        _ => return None,
    })
}
