//! Numpad key definitions.

use super::definition::KeyDefinition;

/// Get numpad key definitions.
pub fn get_numpad_key(key: &str) -> Option<KeyDefinition> {
    Some(match key {
        "Numpad0" => KeyDefinition {
            code: "Numpad0",
            key: "0",
            key_code: 96,
            text: Some("0"),
            is_keypad: true,
            location: 3,
        },
        "Numpad1" => KeyDefinition {
            code: "Numpad1",
            key: "1",
            key_code: 97,
            text: Some("1"),
            is_keypad: true,
            location: 3,
        },
        "Numpad2" => KeyDefinition {
            code: "Numpad2",
            key: "2",
            key_code: 98,
            text: Some("2"),
            is_keypad: true,
            location: 3,
        },
        "Numpad3" => KeyDefinition {
            code: "Numpad3",
            key: "3",
            key_code: 99,
            text: Some("3"),
            is_keypad: true,
            location: 3,
        },
        "Numpad4" => KeyDefinition {
            code: "Numpad4",
            key: "4",
            key_code: 100,
            text: Some("4"),
            is_keypad: true,
            location: 3,
        },
        "Numpad5" => KeyDefinition {
            code: "Numpad5",
            key: "5",
            key_code: 101,
            text: Some("5"),
            is_keypad: true,
            location: 3,
        },
        "Numpad6" => KeyDefinition {
            code: "Numpad6",
            key: "6",
            key_code: 102,
            text: Some("6"),
            is_keypad: true,
            location: 3,
        },
        "Numpad7" => KeyDefinition {
            code: "Numpad7",
            key: "7",
            key_code: 103,
            text: Some("7"),
            is_keypad: true,
            location: 3,
        },
        "Numpad8" => KeyDefinition {
            code: "Numpad8",
            key: "8",
            key_code: 104,
            text: Some("8"),
            is_keypad: true,
            location: 3,
        },
        "Numpad9" => KeyDefinition {
            code: "Numpad9",
            key: "9",
            key_code: 105,
            text: Some("9"),
            is_keypad: true,
            location: 3,
        },
        "NumpadAdd" => KeyDefinition {
            code: "NumpadAdd",
            key: "+",
            key_code: 107,
            text: Some("+"),
            is_keypad: true,
            location: 3,
        },
        "NumpadDecimal" => KeyDefinition {
            code: "NumpadDecimal",
            key: ".",
            key_code: 110,
            text: Some("."),
            is_keypad: true,
            location: 3,
        },
        "NumpadDivide" => KeyDefinition {
            code: "NumpadDivide",
            key: "/",
            key_code: 111,
            text: Some("/"),
            is_keypad: true,
            location: 3,
        },
        "NumpadMultiply" => KeyDefinition {
            code: "NumpadMultiply",
            key: "*",
            key_code: 106,
            text: Some("*"),
            is_keypad: true,
            location: 3,
        },
        "NumpadSubtract" => KeyDefinition {
            code: "NumpadSubtract",
            key: "-",
            key_code: 109,
            text: Some("-"),
            is_keypad: true,
            location: 3,
        },
        _ => return None,
    })
}
